config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :todos, only: %i[index create destroy]

  root to: 'todos#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
# frozen_string_literal: true

class Todo < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
# frozen_string_literal: true

class TodosController < ApplicationController
  def index
    @todos = Todo.order(created_at: :desc)
    @todo = Todo.new
  end

  def create
    todo = Todo.new(todo_params)

    if todo.save
      todo_html = render_to_string(partial: 'todos/todo', locals: { todo: todo }, formats: [:html])
      return render(json: { id: todo.id, html: todo_html }, status: :created)
    end

    render json: { errors: todo.errors.to_h }, status: :unprocessable_entity
  end

  def destroy
    todo = Todo.find_by(id: params[:id])
    todo.destroy

    render plain: '', status: :no_content
  end

  private

  def todo_params
    params.require(:todo).permit(:name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/todos_helper.rb
# frozen_string_literal: true

module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTodo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo.html.erb
<div class="ToDoItem" data-controller="todo-delete" data-target="todo-delete.item">
  <p class="ToDoItem-Text"><%= todo.name %></p>
  <%= button_to "-", todo_path(todo.id),
      method: :delete,
      remote: true,
      form: { data: { action: "ajax:success->todo-delete#successResult ajax:error->todo-delete#errorResult" } },
      class: "ToDoItem-Delete"
     %>
</div>

app/views/todos/index.html.erb
<div class="ToDo">
  <%= image_tag 'logo.png', class: "Logo", alt: "Rails logo" %>
  <h1 class="ToDo-Header">Rails To Do</h1>
  <div class="ToDo-Container" data-controller="todo">
    <div class="ToDo-Content" data-target="todo.todos">
      <%= render @todos %>
    </div>

    <div class="ToDoInput">
      <%= form_with model: @todo, local: false,
        data: { action: "ajax:beforeSend->todo#validateSubmit ajax:error->todo#errorResult ajax:success->todo#successResult" } do |form| %>
        <%= form.text_field :name, data: { target: "todo.field" } %>
        <%= form.submit "+", class: "ToDo-Add" %>
      <% end %>
    </div>
  </div>
</div>